import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Section } from "@/components/LegalPage";
import { PRODUCT_NAME } from "@/config/branding";

export const metadata: Metadata = { title: `Terms of Service — ${PRODUCT_NAME}` };

const CONTACT = "policies@truthcore.ai";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" effectiveDate="July 18, 2026" activeHref="/terms">
      <div className="space-y-3 text-sm leading-relaxed text-fg/50">
        <p>
          Welcome to Debate Night, a live debate game powered by TruthCore (&ldquo;Debate
          Night,&rdquo; the &ldquo;Service&rdquo;). The Service is operated by{" "}
          <span className="font-semibold text-fg/70">TruthCore AI Inc.</span>, a Delaware
          corporation (&ldquo;TruthCore,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;), and is available at{" "}
          <span className="font-semibold text-fg/70">debate.truthcore.ai</span>{" "}(including
          debate.truthcore.ai/join).
        </p>
        <p>
          By accessing or using the Service, you agree to these Terms of Service
          (&ldquo;Terms&rdquo;), our{" "}
          <Link href="/acceptable-use" className="text-brand hover:text-fg">
            Acceptable Use Policy
          </Link>
          , and our{" "}
          <Link href="/privacy" className="text-brand hover:text-fg">
            Privacy Policy
          </Link>
          , which are incorporated into these Terms by reference. If you do not agree, do not use
          the Service.
        </p>
      </div>

      <Section title="1. What Debate Night Is">
        <p>
          Debate Night lets a host create a game room and share a room code with friends. Once at
          least three players have joined, the game begins: two players debate a topic (provided by
          the Service or created by players) over three rounds, other players act as judges and
          select round winners, and the game ends with a recap once an overall winner is
          determined. During a game, judges may type in a claim made by a debater and receive an
          automated fact-check result generated by TruthCore&rsquo;s fact-checking technology.
        </p>
      </Section>

      <Section title="2. Eligibility">
        <p>
          You must be at least <span className="font-semibold text-fg/70">13 years old</span>{" "}to
          use the Service. By using the Service, you represent that you meet this requirement. If
          you are under 18, you represent that you have permission from a parent or legal guardian
          to use the Service.
        </p>
      </Section>

      <Section title="3. No Account Required; Free Service">
        <p>
          The Service does not require you to create an account, and it is currently provided free
          of charge. We may change, suspend, or discontinue the Service (or any feature of it) at
          any time without notice or liability.
        </p>
      </Section>

      <Section title="4. Your Content">
        <p>
          When you use the Service, you may submit content such as display names, debate topics,
          arguments, chat or debate text, and claims submitted for fact-checking (&ldquo;User
          Content&rdquo;). You retain any rights you hold in your User Content. You grant TruthCore
          a worldwide, non-exclusive, royalty-free license to host, store, process, transmit,
          display, and use your User Content as needed to operate, provide, secure, and improve the
          Service, including transmitting claims to third-party service providers for
          fact-checking.
        </p>
        <p>
          You are solely responsible for your User Content. You represent that you have the rights
          necessary to submit it and that it does not violate any law or the rights of any third
          party. We may remove any User Content or end any game session at our discretion.
        </p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>
          Your use of the Service is subject to our{" "}
          <Link href="/acceptable-use" className="text-brand hover:text-fg">
            Acceptable Use Policy
          </Link>
          . Violations may result in removal from games, blocking of access, or other measures we
          consider appropriate.
        </p>
      </Section>

      <Section title="6. Fact-Check Results Disclaimer">
        <p>
          Fact-check results are generated automatically using artificial intelligence and
          third-party data sources.{" "}
          <span className="font-semibold text-fg/70">
            They may be incomplete, outdated, or incorrect.
          </span>{" "}
          Results are provided for informational and entertainment purposes only and do not
          constitute professional, legal, medical, financial, or other advice, and are not a
          definitive determination of truth. You should independently verify any information before
          relying on it. TruthCore does not endorse any claim, debater, topic, or fact-check
          result.
        </p>
      </Section>

      <Section title="7. Intellectual Property">
        <p>
          The Service, including its software, design, branding, and content (excluding User
          Content), is owned by TruthCore or its licensors and is protected by intellectual
          property laws. We grant you a limited, revocable, non-exclusive, non-transferable license
          to use the Service for personal, non-commercial purposes in accordance with these Terms.
          You may not copy, modify, distribute, sell, reverse engineer, scrape, or create
          derivative works from the Service except as permitted by law.
        </p>
      </Section>

      <Section title="8. Feedback">
        <p>
          If you send us feedback or suggestions, you grant us the right to use them without
          restriction or compensation.
        </p>
      </Section>

      <Section title="9. Third-Party Services">
        <p>
          The Service relies on third-party providers (for example, hosting, analytics, and AI
          fact-checking providers). We are not responsible for third-party services, and your use
          of the Service constitutes consent to the processing described in our{" "}
          <Link href="/privacy" className="text-brand hover:text-fg">
            Privacy Policy
          </Link>
          .
        </p>
      </Section>

      <Section title="10. Disclaimer of Warranties">
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; WITHOUT
          WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR UNINTERRUPTED
          AVAILABILITY. WE DO NOT WARRANT THAT FACT-CHECK RESULTS OR ANY OTHER CONTENT WILL BE
          ACCURATE, COMPLETE, OR RELIABLE.
        </p>
      </Section>

      <Section title="11. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRUTHCORE AND ITS OFFICERS, DIRECTORS, EMPLOYEES,
          AND AGENTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, DATA, GOODWILL, OR
          REPUTATION, ARISING OUT OF OR RELATING TO THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY
          OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRUTHCORE&rsquo;S TOTAL
          LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED FIFTY U.S. DOLLARS (US
          $50). SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO SOME OF THESE LIMITATIONS
          MAY NOT APPLY TO YOU.
        </p>
      </Section>

      <Section title="12. Indemnification">
        <p>
          You agree to indemnify and hold harmless TruthCore and its officers, directors,
          employees, and agents from any claims, damages, losses, and expenses (including
          reasonable attorneys&rsquo; fees) arising out of your User Content, your use of the
          Service, or your violation of these Terms or applicable law.
        </p>
      </Section>

      <Section title="13. Dispute Resolution; Arbitration; Class Action Waiver">
        <p className="font-semibold text-fg/70">
          Please read this section carefully — it affects your legal rights.
        </p>
        <p>
          Any dispute arising out of or relating to these Terms or the Service will be resolved by{" "}
          <span className="font-semibold text-fg/70">binding individual arbitration</span>{" "}
          administered by the American Arbitration Association under its Consumer Arbitration
          Rules, rather than in court, except that either party may bring an individual claim in
          small claims court or seek injunctive relief for intellectual property infringement. The
          arbitration will be conducted in English.{" "}
          <span className="font-semibold text-fg/70">
            You and TruthCore each waive the right to a jury trial and the right to participate in
            a class action, class arbitration, or other representative proceeding.
          </span>
        </p>
        <p>
          You may opt out of this arbitration agreement by emailing{" "}
          <a href={`mailto:${CONTACT}`} className="font-semibold text-brand hover:text-fg">
            {CONTACT}
          </a>{" "}
          within 30 days of first using the Service, with your name and a statement that you opt
          out of arbitration.
        </p>
      </Section>

      <Section title="14. Governing Law">
        <p>
          These Terms are governed by the laws of the State of Delaware, without regard to
          conflict-of-laws principles, except as otherwise required by applicable consumer
          protection law.
        </p>
      </Section>

      <Section title="15. Changes to These Terms">
        <p>
          We may update these Terms from time to time. The updated version will be posted at
          debate.truthcore.ai with a revised effective date. Your continued use of the Service
          after changes take effect constitutes acceptance of the updated Terms.
        </p>
      </Section>

      <Section title="16. Termination">
        <p>
          We may suspend or terminate your access to the Service at any time, with or without
          cause or notice. Sections that by their nature should survive termination (including
          Sections 4, 6, 7, and 10–14) will survive.
        </p>
      </Section>

      <Section title="17. Miscellaneous">
        <p>
          These Terms, together with the Acceptable Use Policy and Privacy Policy, are the entire
          agreement between you and TruthCore regarding the Service. If any provision is found
          unenforceable, the remaining provisions remain in effect. Our failure to enforce any
          provision is not a waiver. You may not assign these Terms; we may assign them in
          connection with a merger, acquisition, or sale of assets.
        </p>
      </Section>

      <Section title="18. Contact">
        <p>
          Questions about these Terms:{" "}
          <a href={`mailto:${CONTACT}`} className="font-semibold text-brand hover:text-fg">
            {CONTACT}
          </a>
        </p>
        <p>TruthCore AI Inc.</p>
      </Section>
    </LegalPage>
  );
}
